URL = "https://binaries.hyperliquid.xyz/Testnet/hl-visor"
SlackWebhookURL = "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
CheckInterval = 600
HlVisorService = "hlvisor"
HlVisorPath = "/data/hl-visor" # Don't change if you are using docker
HlNodePath = "/data/hl-node" # Don't change if you are using docker
Automode = true